development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:34c0156b56cfddcf1defe373bfc119aa@scat.redistogo.com:11364/
  channel_prefix: alteri_backend_production
